import type {Metadata} from "next";import Image from "next/image";import {SubFooter,SubHeader,SubHero,styles} from "../components/SubpageShell";import s from "./company.module.css";const s2=s;
export const metadata:Metadata={title:"会社概要 | T-REX CO., LTD.",description:"T-REX株式会社の会社概要。理念・行動基準・会社情報・代表メッセージをご紹介します。"};
const values=[["01","SPEED","止めない対応力","現場の状況を素早く把握し、復旧までの時間を最小限に抑えます。","clock-fast"],["02","QUALITY","妥協しない品質","見えない部分まで丁寧に。長く安心して使える仕上がりを追求します。","shield-quality"],["03","SAFETY","安全を最優先","作業者と現場の安全を守るため、確認と基本動作を徹底します。","shield-safety"],["04","PARTNERSHIP","現場のパートナー","一度きりではなく、困ったときに頼られる存在を目指します。","gear-technology"]];
const profile=[["代表者","中津留 龍也"],["電話番号","090-7531-5428"],["FAX番号","093-967-2347"],["メールアドレス","info@t-rex-works.com"],["営業時間","9:00〜18:00"],["定休日","祝日・日曜日・土曜日（営業日あり）"],["設立年月","2025年1月"],["資本金","300万円"],["法人番号","8290801031174"]];
export default function Page(){return <><SubHeader active="/company"/><main><SubHero en="COMPANY / CORPORATE PROFILE" ja="会社概要" lead="現場を止めないために。T-REXの理念と会社情報をご紹介します。" bg="/company-hero-bg.webp"/>
<section className={`${styles.section} ${styles.light}`}><div className={styles.heading}><p>OUR MISSION</p><h2>現場を止めない。<br/>そのために、できることを。</h2><span>T-REXは、お客様の課題に真摯に向き合い、スピード・品質・安全のすべてに妥協しません。</span></div></section>
<section className={styles.section}><div className={styles.heading}><p>OUR VALUES</p><h2>仕事の基準。</h2></div><div className={styles.grid}>{values.map(([n,en,t,d,i])=><article className={styles.card} key={n}><Image src={`/icons/${i}.svg`} alt="" width={58} height={58}/><small>{n} / {en}</small><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className={`${styles.section} ${styles.light} ${s2.profileBand}`}><div className={styles.heading}><p>PROFILE</p><h2>会社情報</h2></div><dl className={s.profile}>{profile.map(([dt,dd])=><div key={dt}><dt>{dt}</dt><dd>{dt==="電話番号"?<a href="tel:09075315428">{dd}</a>:dt==="メールアドレス"?<a href="mailto:info@t-rex-works.com">{dd}</a>:dd}</dd></div>)}</dl></section>
<section className={styles.section}><div className={s.message}><div><p>MESSAGE</p><h2>代表あいさつ</h2></div><div><p>現場で生まれる一つひとつの課題に誠実に向き合い、確かな技術と迅速な対応で、お客様の仕事を支えてまいります。</p><strong>代表　中津留 龍也</strong></div></div><div className={s.scope}><article><h3>営業・対応範囲</h3><p>福岡県・山口県を中心に、その他の地域も可能な限り対応します。出張修理・持込修理ともに可能です。</p></article><article><h3>主な取引先業種</h3><p>建設機械リース会社、解体業、建設業、土木業、運送業</p></article></div></section></main><SubFooter/></>}
